algoritmo "EX 44"
var

   inicial, final, incremento: Inteiro

inicio

   escreva("DIGITE O VALOR INCIAL: ")
   leia(inicial)

   escreva("DIGITE O VALOR FINAL: ")
   leia(final)

   escreva("DIGITE O INCREMENTO: ")
   leia(incremento)

   Enquanto inicial < final faca
      escreva(inicial)
      inicial <-  inicial + incremento
   FimEnquanto

   escreva(" Acabou !")

fimalgoritmo