algoritmo "ex 5 calcula a  media de duas notas "
var

n1, n2: real
resultado: real
#passou: logico

inicio
      escreval("Digite a primeira nota: ")
      leia(n1)
      escreval("Digite a segunda nota: ")
      leia(n2)
      
      resultado <- (n1 + n2) / 2
      
      #passou <- resultado >=6
      escreval("A media entre",n1, " e" ,n2, " e igual a",resultado)
      
      #escreval(passou)
      
      
      
fimalgoritmo