algoritmo "Aula 3 Entrada de dados."

var
   #n1: caractere
   #n2: caractere
   n1: inteiro
   n2: inteiro
   s: inteiro


inicio
      escreval("Digite um número: ")
      leia(n1)
      escreval("Digite outro número: ")
      leia(n2)
      s <- n1+n2
      escreva("A soma de" , n1 , " e" ,n2, " é igual a ", s)
      

      
      
      #escreval("Digite seu nome: ")
      #leia(n1)
      #escreval("Seja bem vindo ", n1)
      


fimalgoritmo